engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.js"

exclude_paths:
- config/
- db/
- vendor/